solar_system_objects = {'Io': {'mass': 8.931938E22,
                               'radius': 1821.6E3},
                        'Miranda': {'mass': 6.4E19,
                                    'radius': 235.8E3},
                        'Mars': {'mass': 6.4171E23,
                                 'radius': 3389.5E3},
                        'Mimas': {'mass': 3.7493E19,
                                  'radius': 198.2E3},
                        'Iapetus': {'mass': 1.805635E21,
                                    'radius': 734.5E3},
                        'Oberon': {'mass': 3.076E21,
                                   'radius': 761.4E3},
                        'Tethys': {'mass': 6.17449E20,
                                   'radius': 531.1E3},
                        'Venus': {'mass': 4.8675E24,
                                  'radius': 6051.8E3},
                        'Titan': {'mass': 1.3452E23,
                                  'radius': 2574.73E3},
                        'Vesta': {'mass': 2.59076E20,
                                  'radius': 525.4E3/2},
                        'Moon': {'mass': 7.342E22,
                                  'radius': 1737.4E3},
                        }

# Reference: https://www.ranker.com/list/solar-system-mountains-for-base-jumping/michaelgraff
cliffs = {'Verona Rupes': {'height': 20E3,
                           'host': 'Miranda'},
          'Boösaule Montes': {'height': 15E3,
                              'host': 'Io'},
          'Valles Marineris': {'height': 7E3,
                               'host': 'Mars'},
          'Olympus Mons': {'height': 6E3,
                           'host': 'Mars'},
          'Herschel Crater': {'height': 8E3,
                              'host': 'Mimas'},
          'Kasei Valles': {'height': 3E3,
                           'host': 'Mars'},
          'Equatorial Ridge': {'height': 20E3,
                               'host': 'Iapetus'},
          'Unnamed Mountain': {'height': 11E3,
                               'host': 'Oberon'},
          'Mons Huygens': {'height': 5.5E3,
                           'host': 'Moon'},
          'Ithaca Chasma': {'height': 5E3,
                            'host': 'Tethys'},
          'Euboea Montes': {'height': 10.5E3,
                            'host': 'Io'},
          'Skadi Mons': {'height': 11E3,
                         'host': 'Venus'},
          'Mithrim Montes': {'height': 3.337E3,
                             'host': 'Titan'},
          'Rheasilvia': {'height': 22E3,
                         'host': 'Vesta'},
          }